import { Escenario } from './guia-tipos';

/*
 * EL REGISTRO DE RECORRIDOS.
 *
 * Todo lo que Wybix Guide sabe enseñar esta AQUI, como datos. Ningun
 * componente de pantalla sabe que existe un recorrido: solo exponen sus
 * `data-guide`. Añadir un recorrido es añadir una entrada; el motor no cambia.
 *
 * Dos clases:
 *   modo 'guia'  enseña. Señala, explica y espera a que la persona lo haga.
 *                Nunca escribe, guarda ni cobra por ella.
 *   modo 'demo'  actua solo, y SOLO donde el proceso principal confirma una
 *                demostracion segura (ver electron/ipc/guide.js).
 *
 * COMO SE ESCRIBE UN MENSAJE
 *   · Una idea por paso. Una o dos frases cortas: la voz escribe letra a
 *     letra y una frase larga se hace eterna.
 *   · Español de México, de tú, como lo diria alguien que sabe: «Listo. Ya
 *     llegó a Barra.», no «La comanda ha sido enviada exitosamente».
 *   · Nada de nombres internos ni de errores tecnicos.
 *
 * COMO SE SEÑALA
 *   · Por `data-guide`, y en una lista por `data-guide-clave` con un id
 *     estable (el id de la mesa, de la comanda; el SKU). Nunca el texto.
 *   · En una demo, la verdad de cada paso la dice el NEGOCIO (`verifica`,
 *     `logrado`), no el DOM. Ver guia-acciones.ts.
 */

const PRIMER_USO: Escenario = {
  id: 'core.first_run',
  titulo: 'Recorrido inicial',
  descripcion: 'Inicio, venta, inventario, clientes y dónde encontrarme',
  minutos: 3,
  modo: 'guia',
  grupo: 'inicio',
  icono: 'ph-compass',
  pasos: [
    { id: 'hola', ruta: '/dashboard/inicio', cta: 'Empezar',
      mensaje: 'Hola, {nombre}. Te enseño lo esencial de Wybix. Tú decides el ritmo.' },
    { id: 'inicio', objetivo: { guia: 'area-inicio' }, requiere: { areas: ['inicio'] },
      mensaje: 'Inicio te muestra cómo va tu día y qué necesita tu atención.' },
    { id: 'venta', objetivo: { guia: 'area-venta' }, requiere: { areas: ['venta'] },
      mensaje: 'En Venta cobras: buscas el producto, lo agregas y cobras.' },
    /* Hospitality: Mesas y Cocina viven dentro de Venta. */
    { id: 'mesas-cocina', objetivo: { guia: 'area-venta' }, requiere: { areas: ['venta'], capacidades: ['mesas', 'comandas'] },
      mensaje: 'Aquí también están tus Mesas y la Cocina. Cada una tiene su recorrido.' },
    { id: 'mesas', objetivo: { guia: 'area-venta' }, requiere: { areas: ['venta'], capacidades: ['mesas'], sinCapacidades: ['comandas'] },
      mensaje: 'Aquí también están tus Mesas. Tienen su propio recorrido.' },
    { id: 'cocina', objetivo: { guia: 'area-venta' }, requiere: { areas: ['venta'], capacidades: ['comandas'], sinCapacidades: ['mesas'] },
      mensaje: 'Aquí también está la Cocina. Tiene su propio recorrido.' },
    /* Servicios: dice lo que ESTE giro hace primero. */
    { id: 'servicios-agenda', objetivo: { guia: 'area-servicios' }, requiere: { areas: ['servicios'], giro: { inicio: 'agenda' } },
      mensaje: 'En Servicios está tu agenda: las citas del día y quién las atiende.' },
    { id: 'servicios-ordenes', objetivo: { guia: 'area-servicios' }, requiere: { areas: ['servicios'], giro: { inicio: 'ordenes' } },
      mensaje: 'En Servicios están tus órdenes: cada trabajo, desde que llega hasta que lo entregas.' },
    { id: 'inventario', objetivo: { guia: 'area-inventario' }, requiere: { areas: ['inventario'] },
      mensaje: 'En Inventario están tus productos, sus precios y sus existencias.' },
    { id: 'clientes', objetivo: { guia: 'area-clientes' }, requiere: { areas: ['clientes'] },
      mensaje: 'En Clientes guardas a quien te compra, con su crédito y su historial.' },
    { id: 'compras', objetivo: { guia: 'area-compras' }, requiere: { areas: ['compras'] },
      mensaje: 'En Compras registras lo que te llega. El inventario sube solo.' },
    { id: 'buscar', objetivo: { guia: 'buscar' },
      mensaje: '¿Buscas algo? Ctrl+K encuentra pantallas, productos y acciones.' },
    { id: 'guia', objetivo: { guia: 'wybix-guide' }, estado: 'success', cta: 'Terminar',
      mensaje: 'Listo. Aquí me encuentras cuando quieras.' },
  ],
};

const VENTA: Escenario = {
  id: 'core.venta',
  titulo: 'Hacer una venta',
  descripcion: 'Buscar, agregar y cobrar',
  minutos: 2,
  modo: 'guia',
  grupo: 'esencial',
  icono: 'ph-cash-register',
  requiere: { areas: ['venta'] },
  pasos: [
    /* Sin turno, Venta pide abrirlo. Se enseña a proposito, no se topa. */
    { id: 'turno', ruta: '/dashboard/venta', objetivo: { guia: 'turno-modal' }, requiere: { touch: false, turno: false },
      opcional: true, limite: 4000,
      espera: { tipo: 'desaparece', objetivo: { guia: 'turno-modal' } },
      mensaje: 'Antes de vender se abre el turno con el efectivo de la caja. Ábrelo cuando quieras.' },
    /* En escritorio */
    { id: 'agregar', ruta: '/dashboard/venta', objetivo: { guia: 'venta-agregar' }, requiere: { touch: false },
      espera: { tipo: 'pulsa' },
      mensaje: 'Una venta empieza agregando productos. Toca «Agregar producto».' },
    { id: 'buscar', objetivo: { guia: 'venta-buscar' }, requiere: { touch: false },
      espera: { tipo: 'aparece', objetivo: { guia: 'venta-linea' } },
      mensaje: 'Escribe el nombre o el código, y toca el producto.' },
    { id: 'linea', objetivo: { guia: 'venta-linea' }, requiere: { touch: false },
      mensaje: 'Ahí está. La cantidad y el precio se cambian en la misma fila.' },
    { id: 'cobrar', objetivo: { guia: 'venta-cobrar' }, requiere: { touch: false }, cta: 'Entendido',
      mensaje: '«Cobrar» abre el pago. Ese paso lo das tú.' },
    /* En una caja Touch */
    { id: 't-producto', ruta: '/touch', objetivo: { guia: 'touch-producto' }, requiere: { touch: true },
      espera: { tipo: 'aparece', objetivo: { guia: 'touch-linea' } },
      mensaje: 'Toca un producto para agregarlo a la cuenta.' },
    { id: 't-cuenta', objetivo: { guia: 'touch-cuenta' }, requiere: { touch: true },
      mensaje: 'Aquí se arma la cuenta. Con más y menos cambias cantidades.' },
    { id: 't-cobrar', objetivo: { guia: 'touch-cobrar' }, requiere: { touch: true }, cta: 'Entendido',
      mensaje: '«Cobrar» abre el pago: efectivo, tarjeta o transferencia. Ese paso lo das tú.' },
  ],
};

const PRODUCTO: Escenario = {
  id: 'core.producto',
  titulo: 'Crear un producto',
  descripcion: 'Nombre, precio y a vender',
  minutos: 2,
  modo: 'guia',
  grupo: 'esencial',
  icono: 'ph-package',
  requiere: { areas: ['inventario'] },
  pasos: [
    { id: 'agregar', ruta: '/dashboard/inventario', objetivo: { guia: 'agregar-producto' },
      espera: { tipo: 'pulsa' },
      mensaje: 'Vamos a crear un producto. Toca «Agregar producto».' },
    { id: 'nombre', objetivo: { guia: 'producto-nombre' }, espera: { tipo: 'valor' },
      mensaje: 'Primero el nombre, tal como lo verás al vender.' },
    { id: 'precio', objetivo: { guia: 'producto-precio' }, espera: { tipo: 'valor' },
      mensaje: 'Ahora el precio de venta.' },
    { id: 'marca', objetivo: { guia: 'producto-marca' },
      mensaje: 'Elige una marca y una categoría. Ordenan tu catálogo.' },
    { id: 'guardar', objetivo: { guia: 'producto-guardar' },
      espera: { tipo: 'desaparece', objetivo: { guia: 'producto-form' } },
      mensaje: 'Cuando esté listo, «Guardar». Si prefieres no crearlo, cancela.' },
    { id: 'fin', estado: 'success', cta: 'Terminar',
      mensaje: 'Listo. Si tienes muchos, «Importar productos» los carga de una vez.' },
  ],
};

/* En una caja Touch el salon vive dentro de Touch; en escritorio, en el panel. */
const SALON = (c: { touch: boolean }) => (c.touch ? '/touch/mesas' : '/dashboard/mesas');

const MESAS: Escenario = {
  id: 'hospitality.mesas',
  titulo: 'Mesas',
  descripcion: 'El salón, elegir mesa desde la caja y cobrarla',
  minutos: 3,
  modo: 'guia',
  grupo: 'giro',
  icono: 'ph-armchair',
  requiere: { capacidades: ['mesas'] },
  pasos: [
    /* Sin mesas todavia: se dice donde se crean. Opcional: solo si no hay. */
    { id: 'vacio', ruta: SALON, objetivo: { guia: 'mesas-vacio' }, opcional: true,
      mensaje: 'Todavía no hay mesas. Se crean en «Salón y estaciones».' },
    { id: 'salon', ruta: SALON, objetivo: { guia: 'mesas-salon' }, opcional: true,
      mensaje: 'Este es tu salón. Libres en gris, abiertas en cyan y por cobrar en ámbar.' },
    { id: 'sin-mesa', objetivo: { guia: 'mesas-cuenta-sin-mesa' },
      mensaje: 'Para la barra o un pedido para llevar, abre una cuenta sin mesa.' },
    /* En una caja Touch: la mesa se elige sin salir de Venta. */
    { id: 'aqui', ruta: '/touch', objetivo: { guia: 'venta-servicio' }, requiere: { touch: true },
      espera: { tipo: 'pulsa' },
      mensaje: 'En la caja, «Aquí» te deja elegir la mesa sin salir de Venta. Tócalo.' },
    { id: 'elige', objetivo: { guia: 'mesas-selector' }, requiere: { touch: true },
      espera: { tipo: 'desaparece', objetivo: { guia: 'mesas-selector' } },
      mensaje: 'Elige una mesa, o toca «Sin mesa».' },
    { id: 'cuenta', objetivo: { guia: 'touch-cuenta' }, requiere: { touch: true },
      mensaje: 'Lo que tomas queda pendiente. «Enviar a preparación» lo manda a su estación.' },
    { id: 'cobrar', objetivo: { guia: 'touch-cobrar' }, requiere: { touch: true }, estado: 'success', cta: 'Terminar',
      mensaje: 'Cuando pidan la cuenta, se cobra aquí. La mesa queda libre sola.' },
    /* En escritorio: la mesa se abre desde el salon y lleva a Venta. */
    { id: 'abrir', objetivo: { guia: 'salon-mesa' }, requiere: { touch: false }, opcional: true,
      mensaje: 'Toca una mesa para abrirla. Te lleva a Venta con su cuenta.' },
    { id: 'venta', ruta: '/dashboard/venta', objetivo: { guia: 'venta-agregar' }, requiere: { touch: false },
      mensaje: 'En Venta tomas el pedido como siempre, y lo envías a preparación.' },
    { id: 'cobro', objetivo: { guia: 'venta-cobrar' }, requiere: { touch: false }, estado: 'success', cta: 'Terminar',
      mensaje: 'Al cobrar, la mesa se libera sola.' },
  ],
};

const COCINA: Escenario = {
  id: 'hospitality.cocina',
  titulo: 'Cocina',
  descripcion: 'Estaciones y cómo avanza cada comanda',
  minutos: 2,
  modo: 'guia',
  grupo: 'giro',
  icono: 'ph-cooking-pot',
  requiere: { capacidades: ['comandas'] },
  pasos: [
    { id: 'estaciones', ruta: '/cocina', objetivo: { guia: 'kds-estaciones' },
      mensaje: 'Esta pantalla se queda abierta en la barra o en la cocina. Cada estación ve lo suyo.' },
    { id: 'comandas', objetivo: { guia: 'kds-comandas' },
      mensaje: 'Las comandas pasan de Nuevas a En preparación y a Listas. El reloj avisa si alguna se atrasa.' },
    { id: 'paso', objetivo: { guia: 'kds-paso' }, opcional: true,
      mensaje: 'Un toque la avanza. La caja se entera sola.' },
    { id: 'salir', objetivo: { guia: 'kds-salir' }, estado: 'success', cta: 'Terminar',
      mensaje: 'Con la flecha vuelves a la caja.' },
  ],
};

/* ====================================================================
   SERVICIOS: uno por forma de trabajar; el giro decide cual se ve
   ==================================================================== */

/* Cualquier pestaña de Servicios vale: solo se navega si se esta fuera. */
const SERVICIOS = '/dashboard/ordenes-de-servicio/**';

const SERVICIOS_ORDENES: Escenario = {
  id: 'servicios.ordenes',
  titulo: 'Recibir un trabajo',
  descripcion: 'La orden, el cliente y lo que se pide',
  minutos: 3,
  modo: 'guia',
  grupo: 'giro',
  icono: 'ph-wrench',
  requiere: { areas: ['servicios'], giro: { inicio: 'ordenes' } },
  pasos: [
    { id: 'ordenes', ruta: '/dashboard/ordenes-de-servicio/ordenes', objetivo: { guia: 'srv-tab-ordenes' },
      mensaje: 'Aquí vive el trabajo: cada orden con su estado, de recibida a entregada.' },
    { id: 'nueva', objetivo: { guia: 'srv-nueva-orden' }, espera: { tipo: 'pulsa' },
      mensaje: 'Un trabajo nuevo empieza en «Nueva orden». Tócalo; nada se guarda sin que lo digas.' },
    /* Opcionales: sin clientes, «Nueva orden» avisa y lleva a Clientes, y el
       formulario no llega a abrirse. El primero espera mas: abre tras cargar. */
    { id: 'cliente-activo', objetivo: { guia: 'srv-orden-cliente' }, requiere: { giro: { usaActivos: true } },
      opcional: true, limite: 6000,
      mensaje: 'Primero, de quién es. Al elegir al cliente aparece su {activo}.' },
    { id: 'cliente', objetivo: { guia: 'srv-orden-cliente' }, requiere: { giro: { usaActivos: false } },
      opcional: true, limite: 6000,
      mensaje: 'Primero, de quién es. Si es nuevo, lo das de alta en Clientes.' },
    { id: 'reportado', objetivo: { guia: 'srv-orden-reportado' }, opcional: true,
      mensaje: 'Aquí va lo que te piden, con las palabras del cliente. Cotizar puede esperar.' },
    { id: 'abrir', objetivo: { guia: 'srv-orden-abrir' }, opcional: true, cta: 'Entendido',
      mensaje: '«Abrir orden» la crea. Si solo estabas mirando, «Cancelar».' },
    { id: 'activos', ruta: '/dashboard/ordenes-de-servicio/activos', objetivo: { guia: 'srv-tab-activos' },
      requiere: { giro: { usaActivos: true } },
      mensaje: 'En {Activos} está cada uno con su historial: qué se le hizo y cuándo.' },
    /* Con ruta: si el aviso «Primero, un cliente» llevo a Clientes, se vuelve. */
    { id: 'agenda', ruta: SERVICIOS, objetivo: { guia: 'srv-tab-agenda' }, requiere: { giro: { usaAgenda: true } },
      mensaje: 'En Agenda están las visitas y citas del día.' },
    { id: 'fin', ruta: SERVICIOS, objetivo: { guia: 'srv-tab-ordenes' }, estado: 'success', cta: 'Terminar',
      mensaje: 'Cuando el trabajo termina, se cobra desde la misma orden.' },
  ],
};

const SERVICIOS_AGENDA: Escenario = {
  id: 'servicios.agenda',
  titulo: 'Tu agenda',
  descripcion: 'El día, las citas y quién atiende',
  minutos: 3,
  modo: 'guia',
  grupo: 'giro',
  icono: 'ph-calendar-dots',
  requiere: { areas: ['servicios'], giro: { inicio: 'agenda' } },
  pasos: [
    { id: 'dia', ruta: '/dashboard/ordenes-de-servicio/agenda', objetivo: { guia: 'srv-agenda-dia' },
      mensaje: 'Tu día de un vistazo. Con las flechas cambias de día; «Hoy» te regresa.' },
    { id: 'rejilla', objetivo: { guia: 'srv-agenda-rejilla' },
      mensaje: 'Cada columna es quien atiende y cada bloque, una cita. Tocar una hora libre también agenda.' },
    { id: 'nueva', objetivo: { guia: 'srv-nueva-cita' }, espera: { tipo: 'pulsa' },
      mensaje: 'Una cita nueva empieza aquí. Tócalo; nada se guarda sin que lo digas.' },
    /* Opcionales: sin clientes, la agenda pide dar de alta uno primero y el
       formulario no llega a abrirse. */
    { id: 'cliente', objetivo: { guia: 'srv-cita-cliente' }, opcional: true, limite: 6000,
      mensaje: 'Quién viene…' },
    { id: 'servicio', objetivo: { guia: 'srv-cita-servicio' }, opcional: true,
      mensaje: '…qué se va a hacer. Su duración aparta el tiempo en la agenda…' },
    { id: 'agendar', objetivo: { guia: 'srv-cita-agendar' }, opcional: true, cta: 'Entendido',
      mensaje: '…y «Agendar». Si solo estabas mirando, «Cancelar».' },
    { id: 'clientes', objetivo: { guia: 'area-clientes' }, requiere: { areas: ['clientes'] },
      mensaje: 'Una cita siempre es de alguien. Tus clientes están en Clientes.' },
    { id: 'fin', ruta: '/dashboard/ordenes-de-servicio/agenda', objetivo: { guia: 'srv-tab-ordenes' },
      estado: 'success', cta: 'Terminar',
      mensaje: 'Cuando el cliente llega, la cita se vuelve una orden y se cobra ahí mismo.' },
  ],
};

/* ====================================================================
   DEMOSTRACIONES AUTOMATICAS
   Cada una declara lo que necesita (`necesita`) y lo prepara antes del
   primer paso (`prepara`, guia-acciones.ts). Cada paso dice que hecho del
   negocio lo confirma (`verifica`) y cuando ya esta hecho (`logrado`).
   ==================================================================== */

const DEMO_RETAIL: Escenario = {
  id: 'demo.retail',
  titulo: 'Crear y vender un producto',
  descripcion: 'Wybix lo hace solo mientras tú lo cuentas',
  minutos: 1,
  modo: 'demo',
  grupo: 'demo',
  icono: 'ph-play-circle',
  requiere: { areas: ['inventario', 'venta'] },
  prepara: true,
  necesita: ['Marca «General» y categoría «General» (se crean si faltan)', 'El producto de la vuelta anterior, archivado', 'Turno abierto'],
  verificaFinal: 'retail.vendido',
  pasos: [
    { id: 'hola', ruta: '/dashboard/inicio',
      mensaje: 'Te enseño Wybix en un minuto: creo un producto y lo vendo.',
      acciones: [{ tipo: 'pausa', ms: 400 }] },
    { id: 'agregar', ruta: '/dashboard/inventario', objetivo: { guia: 'agregar-producto' },
      mensaje: 'Todo empieza en Inventario. Agrego un producto.',
      logrado: { tipo: 'hecho', nombre: 'retail.producto-creado' },
      acciones: [{ tipo: 'pulsar', objetivo: { guia: 'agregar-producto' } }],
      despues: { tipo: 'aparece', objetivo: { guia: 'producto-nombre' } } },
    { id: 'marca', objetivo: { guia: 'producto-marca' },
      mensaje: 'Le pongo marca y categoría.',
      logrado: { tipo: 'hecho', nombre: 'retail.producto-creado' },
      acciones: [
        { tipo: 'elegir', objetivo: { guia: 'producto-marca' }, valor: '{mem.marcaId}' },
        { tipo: 'elegir', objetivo: { guia: 'producto-categoria' }, valor: '{mem.categoriaId}' },
      ] },
    { id: 'sku', objetivo: { guia: 'producto-sku' },
      mensaje: 'Su código…',
      logrado: { tipo: 'hecho', nombre: 'retail.producto-creado' },
      acciones: [{ tipo: 'escribir', objetivo: { guia: 'producto-sku' }, texto: 'DEMO-GUIA-CAFE' }] },
    { id: 'nombre', objetivo: { guia: 'producto-nombre' },
      mensaje: '…su nombre…',
      logrado: { tipo: 'hecho', nombre: 'retail.producto-creado' },
      acciones: [{ tipo: 'escribir', objetivo: { guia: 'producto-nombre' }, texto: 'Café de la demo' }] },
    { id: 'precio', objetivo: { guia: 'producto-precio' },
      mensaje: '…y su precio: 65 pesos.',
      logrado: { tipo: 'hecho', nombre: 'retail.producto-creado' },
      acciones: [{ tipo: 'escribir', objetivo: { guia: 'producto-precio' }, texto: '65' }] },
    { id: 'stock', objetivo: { guia: 'producto-stock' }, opcional: true,
      mensaje: 'Tengo 20.',
      logrado: { tipo: 'hecho', nombre: 'retail.producto-creado' },
      acciones: [{ tipo: 'escribir', objetivo: { guia: 'producto-stock' }, texto: '20' }] },
    { id: 'guardar', objetivo: { guia: 'producto-guardar' },
      mensaje: 'Lo guardo.',
      logrado: { tipo: 'hecho', nombre: 'retail.producto-creado' },
      acciones: [{ tipo: 'pulsar', objetivo: { guia: 'producto-guardar' } }],
      verifica: 'retail.producto-creado' },
    /* Vender, en escritorio… */
    { id: 'venta', ruta: '/dashboard/venta', objetivo: { guia: 'venta-agregar' }, requiere: { touch: false },
      mensaje: 'Ya está en el catálogo. Ahora lo vendo.',
      logrado: { tipo: 'hecho', nombre: 'retail.en-la-venta' },
      acciones: [{ tipo: 'pulsar', objetivo: { guia: 'venta-agregar' } }],
      despues: { tipo: 'aparece', objetivo: { guia: 'venta-buscar' } } },
    { id: 'busca', objetivo: { guia: 'venta-buscar' }, requiere: { touch: false },
      mensaje: 'Lo busco por su nombre…',
      logrado: { tipo: 'hecho', nombre: 'retail.en-la-venta' },
      acciones: [{ tipo: 'escribir', objetivo: { guia: 'venta-buscar' }, texto: 'Café de la demo' }] },
    { id: 'agrega', objetivo: { guia: 'venta-producto', clave: '{mem.sku}' }, requiere: { touch: false },
      mensaje: '…y lo agrego.',
      logrado: { tipo: 'hecho', nombre: 'retail.en-la-venta' },
      acciones: [{ tipo: 'pulsar', objetivo: { guia: 'venta-producto', clave: '{mem.sku}' } }],
      verifica: 'retail.en-la-venta' },
    { id: 'cobrar', ruta: '/dashboard/venta', objetivo: { guia: 'venta-cobrar' }, requiere: { touch: false },
      mensaje: 'Cobro.',
      logrado: { tipo: 'hecho', nombre: 'retail.vendido' },
      acciones: [{ tipo: 'pulsar', objetivo: { guia: 'venta-cobrar' } }],
      despues: { tipo: 'aparece', objetivo: { guia: 'venta-recibido' } } },
    { id: 'pago', objetivo: { guia: 'venta-recibido' }, requiere: { touch: false },
      mensaje: 'En efectivo: me pagan con 100.',
      logrado: { tipo: 'hecho', nombre: 'retail.vendido' },
      acciones: [
        { tipo: 'pulsar', objetivo: { guia: 'venta-pago-efectivo' } },
        { tipo: 'escribir', objetivo: { guia: 'venta-recibido' }, texto: '100' },
        { tipo: 'pulsar', objetivo: { guia: 'venta-confirmar-cobro' } },
      ],
      verifica: 'retail.vendido' },
    /* …o en una caja Touch. */
    { id: 't-agrega', ruta: '/touch', objetivo: { guia: 'touch-producto', clave: '{mem.sku}' }, requiere: { touch: true },
      mensaje: 'Ya está en el catálogo. Lo toco para venderlo.',
      logrado: { tipo: 'hecho', nombre: 'retail.en-la-venta' },
      acciones: [{ tipo: 'pulsar', objetivo: { guia: 'touch-producto', clave: '{mem.sku}' } }],
      verifica: 'retail.en-la-venta' },
    { id: 't-cobrar', ruta: '/touch', objetivo: { guia: 'touch-cobrar' }, requiere: { touch: true },
      mensaje: 'Cobro en efectivo.',
      logrado: { tipo: 'hecho', nombre: 'retail.vendido' },
      acciones: [
        { tipo: 'pulsar', objetivo: { guia: 'touch-cobrar' } },
        { tipo: 'pulsar', objetivo: { guia: 'touch-cobro-rapido' } },
        { tipo: 'pausa', ms: 300 },
        { tipo: 'pulsar', objetivo: { guia: 'touch-cobro-confirmar' } },
      ],
      verifica: 'retail.vendido' },
    { id: 'fin', estado: 'success',
      mensaje: 'Listo. Creado y vendido en un minuto.',
      acciones: [{ tipo: 'pausa', ms: 900 }] },
  ],
};

const DEMO_HOSPITALITY: Escenario = {
  id: 'demo.hospitality',
  titulo: 'Cafetería: de la mesa a la cocina',
  descripcion: 'Mesa, pedido, preparación, cobro y horarios',
  minutos: 2,
  modo: 'demo',
  grupo: 'demo',
  icono: 'ph-coffee',
  requiere: { perfilDemo: ['hospitality'] },
  prepara: true,
  necesita: ['Módulos Hospitality, Mesas y Comandas encendidos', 'Estación «Barra»', 'Americano Demo asignado a la Barra',
    'Salón con la Mesa 1 libre', 'La cocina sin comandas de vueltas anteriores', 'Turno abierto'],
  verificaFinal: 'hosp.cobrada',
  pasos: [
    { id: 'hola',
      mensaje: 'Una cafetería con Wybix: tomo un pedido en la Mesa 1 y lo sigo hasta el cobro.',
      acciones: [{ tipo: 'pausa', ms: 300 }] },

    /* ---- La mesa, en una caja Touch… */
    { id: 'aqui', ruta: '/touch', objetivo: { guia: 'venta-servicio' }, requiere: { touch: true },
      mensaje: '«Aquí» es para comer en el local. Elijo la mesa sin salir de la caja.',
      logrado: { tipo: 'hecho', nombre: 'hosp.mesa-abierta' },
      acciones: [{ tipo: 'pulsar', objetivo: { guia: 'venta-servicio' } }],
      despues: { tipo: 'aparece', objetivo: { guia: 'mesas-selector' } } },
    { id: 'mesa', objetivo: { guia: 'mesa', clave: '{mem.mesaId}' }, requiere: { touch: true },
      mensaje: 'La Mesa 1.',
      logrado: { tipo: 'hecho', nombre: 'hosp.mesa-abierta' },
      acciones: [{ tipo: 'pulsar', objetivo: { guia: 'mesa', clave: '{mem.mesaId}' } }],
      verifica: 'hosp.mesa-abierta' },
    { id: 'producto', ruta: '/touch', objetivo: { guia: 'touch-producto', clave: '{mem.sku}' }, requiere: { touch: true },
      mensaje: 'Un americano.',
      logrado: { tipo: 'hecho', nombre: 'hosp.en-la-cuenta' },
      acciones: [{ tipo: 'pulsar', objetivo: { guia: 'touch-producto', clave: '{mem.sku}' } }],
      verifica: 'hosp.en-la-cuenta' },
    { id: 'enviar', ruta: '/touch', objetivo: { guia: 'touch-enviar' }, requiere: { touch: true },
      mensaje: 'Lo mando a preparación.',
      logrado: { tipo: 'hecho', nombre: 'hosp.enviada' },
      acciones: [{ tipo: 'pulsar', objetivo: { guia: 'touch-enviar' } }],
      verifica: 'hosp.enviada' },

    /* ---- …o en escritorio: el salon abre Venta con la cuenta. */
    { id: 'salon', ruta: '/dashboard/mesas', objetivo: { guia: 'salon-mesa', clave: '{mem.mesaId}' }, requiere: { touch: false },
      mensaje: 'Este es el salón. Abro la Mesa 1.',
      logrado: { tipo: 'hecho', nombre: 'hosp.mesa-abierta' },
      acciones: [{ tipo: 'pulsar', objetivo: { guia: 'salon-mesa', clave: '{mem.mesaId}' } }],
      verifica: 'hosp.mesa-abierta' },
    { id: 'agregar', ruta: '/dashboard/venta', objetivo: { guia: 'venta-agregar' }, requiere: { touch: false },
      mensaje: 'Agrego un americano.',
      logrado: { tipo: 'hecho', nombre: 'hosp.en-la-cuenta' },
      acciones: [{ tipo: 'pulsar', objetivo: { guia: 'venta-agregar' } }],
      despues: { tipo: 'aparece', objetivo: { guia: 'venta-buscar' } } },
    { id: 'busca', objetivo: { guia: 'venta-buscar' }, requiere: { touch: false },
      mensaje: 'Lo busco…',
      logrado: { tipo: 'hecho', nombre: 'hosp.en-la-cuenta' },
      acciones: [{ tipo: 'escribir', objetivo: { guia: 'venta-buscar' }, texto: 'Americano' }] },
    { id: 'agrega', objetivo: { guia: 'venta-producto', clave: '{mem.sku}' }, requiere: { touch: false },
      mensaje: '…y lo agrego a la cuenta.',
      logrado: { tipo: 'hecho', nombre: 'hosp.en-la-cuenta' },
      acciones: [{ tipo: 'pulsar', objetivo: { guia: 'venta-producto', clave: '{mem.sku}' } }],
      verifica: 'hosp.en-la-cuenta' },
    { id: 'enviar-e', ruta: '/dashboard/venta', objetivo: { guia: 'venta-enviar-mesa' }, requiere: { touch: false },
      mensaje: 'Lo mando a preparación.',
      logrado: { tipo: 'hecho', nombre: 'hosp.enviada' },
      acciones: [{ tipo: 'pulsar', objetivo: { guia: 'venta-enviar-mesa' } }],
      verifica: 'hosp.enviada' },

    /* ---- La cocina: SU comanda, por su id. */
    { id: 'cocina', ruta: '/cocina', objetivo: { guia: 'kds-ticket', clave: '{mem.comandaId}' },
      mensaje: 'Listo. Ya llegó a Barra.',
      logrado: { tipo: 'hecho', nombre: 'hosp.preparando' },
      verifica: 'hosp.enviada' },
    { id: 'prepara', ruta: '/cocina', objetivo: { guia: 'kds-paso', clave: '{mem.comandaId}' },
      mensaje: 'En la barra lo empiezan…',
      logrado: { tipo: 'hecho', nombre: 'hosp.preparando' },
      acciones: [{ tipo: 'pulsar', objetivo: { guia: 'kds-paso', clave: '{mem.comandaId}' } }],
      verifica: 'hosp.preparando' },
    { id: 'lista', ruta: '/cocina', objetivo: { guia: 'kds-paso', clave: '{mem.comandaId}' },
      mensaje: '…y lo marcan listo. La caja ya lo sabe.',
      logrado: { tipo: 'hecho', nombre: 'hosp.lista' },
      acciones: [{ tipo: 'pulsar', objetivo: { guia: 'kds-paso', clave: '{mem.comandaId}' } }],
      verifica: 'hosp.lista' },

    /* ---- El cobro, en Touch… */
    { id: 'cobrar', ruta: '/touch', objetivo: { guia: 'touch-cobrar' }, requiere: { touch: true },
      mensaje: 'Cuando piden la cuenta, cobro aquí mismo.',
      logrado: { tipo: 'hecho', nombre: 'hosp.cobrada' },
      acciones: [{ tipo: 'pulsar', objetivo: { guia: 'touch-cobrar' } }],
      despues: { tipo: 'aparece', objetivo: { guia: 'touch-cobro-rapido' } } },
    { id: 'pago', objetivo: { guia: 'touch-cobro-confirmar' }, requiere: { touch: true },
      mensaje: 'En efectivo. La mesa queda libre sola.',
      logrado: { tipo: 'hecho', nombre: 'hosp.cobrada' },
      acciones: [{ tipo: 'pulsar', objetivo: { guia: 'touch-cobro-rapido' } }, { tipo: 'pausa', ms: 300 },
                 { tipo: 'pulsar', objetivo: { guia: 'touch-cobro-confirmar' } }],
      verifica: 'hosp.cobrada' },
    /* ---- …o en escritorio. */
    { id: 'cobrar-e', ruta: '/dashboard/venta', objetivo: { guia: 'venta-cobrar' }, requiere: { touch: false },
      mensaje: 'Cuando piden la cuenta, cobro desde Venta.',
      logrado: { tipo: 'hecho', nombre: 'hosp.cobrada' },
      acciones: [{ tipo: 'pulsar', objetivo: { guia: 'venta-cobrar' } }],
      despues: { tipo: 'aparece', objetivo: { guia: 'venta-recibido' } } },
    { id: 'pago-e', objetivo: { guia: 'venta-recibido' }, requiere: { touch: false },
      mensaje: 'En efectivo. La mesa queda libre sola.',
      logrado: { tipo: 'hecho', nombre: 'hosp.cobrada' },
      acciones: [
        { tipo: 'pulsar', objetivo: { guia: 'venta-pago-efectivo' } },
        { tipo: 'escribir', objetivo: { guia: 'venta-recibido' }, texto: '100' },
        { tipo: 'pulsar', objetivo: { guia: 'venta-confirmar-cobro' } },
      ],
      verifica: 'hosp.cobrada' },

    { id: 'horarios', ruta: '/dashboard/estadisticas', objetivo: { guia: 'est-horarios' },
      mensaje: 'Y al cerrar el día, ves a qué horas se llena tu cafetería.',
      acciones: [{ tipo: 'pulsar', objetivo: { guia: 'est-horarios' } }, { tipo: 'pausa', ms: 900 }] },
    { id: 'fin', estado: 'success',
      mensaje: 'Listo: mesa, cocina, cobro y horarios.',
      acciones: [{ tipo: 'pausa', ms: 700 }] },
  ],
};

const DEMO_TALLER: Escenario = {
  id: 'demo.services.workshop',
  titulo: 'Taller: del coche que llega al trabajo cobrado',
  descripcion: 'Orden, vehículo, cotización, autorización, trabajo y cobro',
  minutos: 2,
  modo: 'demo',
  grupo: 'demo',
  icono: 'ph-wrench',
  requiere: { perfilDemo: ['servicios'], presetDemo: ['TALLER_AUTOMOTRIZ'], touch: false },
  prepara: true,
  necesita: ['Cliente «David Demo» con su Mazda 3 (ABC-123), de la semilla del giro', 'Servicio «Cambio de aceite»',
    'Las órdenes a medias de vueltas anteriores, canceladas', 'Turno abierto'],
  verificaFinal: 'srv.cobrada',
  pasos: [
    { id: 'hola', ruta: '/dashboard/ordenes-de-servicio/ordenes',
      mensaje: 'Un taller con Wybix: recibo un coche, hago el trabajo y lo cobro.',
      acciones: [{ tipo: 'pausa', ms: 300 }] },
    { id: 'nueva', ruta: '/dashboard/ordenes-de-servicio/ordenes', objetivo: { guia: 'srv-nueva-orden' },
      mensaje: 'Llega David con su coche. Abro una orden.',
      logrado: { tipo: 'hecho', nombre: 'srv.orden-abierta' },
      acciones: [{ tipo: 'pulsar', objetivo: { guia: 'srv-nueva-orden' } }],
      despues: { tipo: 'aparece', objetivo: { guia: 'srv-orden-cliente' } } },
    { id: 'cliente', objetivo: { guia: 'srv-orden-cliente' },
      mensaje: 'Es David…',
      logrado: { tipo: 'hecho', nombre: 'srv.orden-abierta' },
      acciones: [{ tipo: 'elegir', objetivo: { guia: 'srv-orden-cliente' }, valor: '{mem.clienteId}' }],
      despues: { tipo: 'aparece', objetivo: { guia: 'srv-orden-activo' } } },
    { id: 'vehiculo', objetivo: { guia: 'srv-orden-activo' },
      mensaje: '…con su Mazda 3.',
      logrado: { tipo: 'hecho', nombre: 'srv.orden-abierta' },
      acciones: [{ tipo: 'elegir', objetivo: { guia: 'srv-orden-activo' }, valor: '{mem.activoId}' }] },
    { id: 'reportado', objetivo: { guia: 'srv-orden-reportado' },
      mensaje: 'Anoto lo que reporta.',
      logrado: { tipo: 'hecho', nombre: 'srv.orden-abierta' },
      acciones: [{ tipo: 'escribir', objetivo: { guia: 'srv-orden-reportado' }, texto: 'Toca cambio de aceite.' }] },
    { id: 'abrir', objetivo: { guia: 'srv-orden-abrir' },
      mensaje: 'Abro la orden.',
      logrado: { tipo: 'hecho', nombre: 'srv.orden-abierta' },
      acciones: [{ tipo: 'pulsar', objetivo: { guia: 'srv-orden-abrir' } }],
      verifica: 'srv.orden-abierta' },
    { id: 'servicio', objetivo: { guia: 'srv-orden-agregar-servicio' },
      mensaje: 'Cotizo el trabajo: un cambio de aceite.',
      logrado: { tipo: 'hecho', nombre: 'srv.linea-agregada' },
      acciones: [{ tipo: 'pulsar', objetivo: { guia: 'srv-orden-agregar-servicio' } }],
      despues: { tipo: 'aparece', objetivo: { guia: 'srv-linea-item' } } },
    { id: 'elige', objetivo: { guia: 'srv-linea-item' },
      mensaje: 'Lo elijo del catálogo…',
      logrado: { tipo: 'hecho', nombre: 'srv.linea-agregada' },
      acciones: [{ tipo: 'elegir', objetivo: { guia: 'srv-linea-item' }, valor: '{mem.servicioId}' }] },
    { id: 'anade', objetivo: { guia: 'srv-linea-confirmar' },
      mensaje: '…y lo agrego a la orden.',
      logrado: { tipo: 'hecho', nombre: 'srv.linea-agregada' },
      acciones: [{ tipo: 'pulsar', objetivo: { guia: 'srv-linea-confirmar' } }],
      verifica: 'srv.linea-agregada' },
    { id: 'autoriza', objetivo: { guia: 'srv-orden-autorizar' },
      mensaje: 'David lo aprueba por teléfono. Lo registro.',
      logrado: { tipo: 'hecho', nombre: 'srv.autorizada' },
      acciones: [{ tipo: 'pulsar', objetivo: { guia: 'srv-orden-autorizar' } }],
      despues: { tipo: 'aparece', objetivo: { guia: 'srv-autorizacion-nombre' } } },
    { id: 'quien', objetivo: { guia: 'srv-autorizacion-nombre' },
      mensaje: 'Quién autoriza…',
      logrado: { tipo: 'hecho', nombre: 'srv.autorizada' },
      acciones: [
        { tipo: 'escribir', objetivo: { guia: 'srv-autorizacion-nombre' }, texto: 'David Demo' },
        { tipo: 'pulsar', objetivo: { guia: 'srv-autorizacion-confirmar' } },
      ],
      verifica: 'srv.autorizada' },
    { id: 'proceso', objetivo: { guia: 'srv-orden-en-proceso' },
      mensaje: 'El mecánico empieza el trabajo…',
      logrado: { tipo: 'hecho', nombre: 'srv.en-proceso' },
      acciones: [{ tipo: 'pulsar', objetivo: { guia: 'srv-orden-en-proceso' } }],
      verifica: 'srv.en-proceso' },
    { id: 'hecho', objetivo: { guia: 'srv-linea-estado', clave: '{mem.servicioId}' },
      mensaje: 'Cuando acaba, marca el trabajo como hecho…',
      logrado: { tipo: 'hecho', nombre: 'srv.linea-hecha' },
      acciones: [{ tipo: 'elegir', objetivo: { guia: 'srv-linea-estado', clave: '{mem.servicioId}' }, valor: 'HECHA' }],
      verifica: 'srv.linea-hecha' },
    { id: 'termina', objetivo: { guia: 'srv-orden-terminar' },
      mensaje: '…y cierra la orden.',
      logrado: { tipo: 'hecho', nombre: 'srv.terminada' },
      acciones: [{ tipo: 'pulsar', objetivo: { guia: 'srv-orden-terminar' } }],
      verifica: 'srv.terminada' },
    { id: 'cobrar', objetivo: { guia: 'srv-orden-cobrar' },
      mensaje: 'Lo cobro desde la misma orden.',
      logrado: { tipo: 'hecho', nombre: 'srv.cobrada' },
      acciones: [{ tipo: 'pulsar', objetivo: { guia: 'srv-orden-cobrar' } }],
      despues: { tipo: 'aparece', objetivo: { guia: 'venta-cobrar' } } },
    { id: 'venta', objetivo: { guia: 'venta-cobrar' },
      mensaje: 'La venta ya trae el trabajo.',
      logrado: { tipo: 'hecho', nombre: 'srv.cobrada' },
      acciones: [{ tipo: 'pulsar', objetivo: { guia: 'venta-cobrar' } }],
      despues: { tipo: 'aparece', objetivo: { guia: 'venta-recibido' } } },
    { id: 'pago', objetivo: { guia: 'venta-recibido' },
      mensaje: 'En efectivo.',
      logrado: { tipo: 'hecho', nombre: 'srv.cobrada' },
      acciones: [
        { tipo: 'pulsar', objetivo: { guia: 'venta-pago-efectivo' } },
        { tipo: 'escribir', objetivo: { guia: 'venta-recibido' }, texto: '1000' },
        { tipo: 'pulsar', objetivo: { guia: 'venta-confirmar-cobro' } },
      ],
      verifica: 'srv.cobrada' },
    { id: 'fin', estado: 'success',
      mensaje: 'Listo. La orden queda cobrada, con su historial en el vehículo.',
      acciones: [{ tipo: 'pausa', ms: 700 }] },
  ],
};

const DEMO_BELLEZA: Escenario = {
  id: 'demo.services.beauty',
  titulo: 'Estética: de la cita al cobro',
  descripcion: 'Agendar, atender y cobrar',
  minutos: 2,
  modo: 'demo',
  grupo: 'demo',
  icono: 'ph-scissors',
  requiere: { perfilDemo: ['servicios'], presetDemo: ['BELLEZA'], touch: false },
  prepara: true,
  necesita: ['Clienta «Mariana López», servicio «Corte de cabello» y estilista «Ana Torres», de la semilla del giro',
    'Las citas y órdenes a medias de Mariana, canceladas', 'Turno abierto'],
  verificaFinal: 'srv.cobrada',
  pasos: [
    { id: 'hola', ruta: '/dashboard/ordenes-de-servicio/agenda',
      mensaje: 'Una estética con Wybix: agendo una cita, la atiendo y la cobro.',
      acciones: [{ tipo: 'pausa', ms: 300 }] },
    { id: 'nueva', ruta: '/dashboard/ordenes-de-servicio/agenda', objetivo: { guia: 'srv-nueva-cita' },
      mensaje: 'Mariana llama para un corte. Le hago una cita.',
      logrado: { tipo: 'hecho', nombre: 'srv.cita-agendada' },
      acciones: [{ tipo: 'pulsar', objetivo: { guia: 'srv-nueva-cita' } }],
      despues: { tipo: 'aparece', objetivo: { guia: 'srv-cita-cliente' } } },
    { id: 'cliente', objetivo: { guia: 'srv-cita-cliente' },
      mensaje: 'Para Mariana…',
      logrado: { tipo: 'hecho', nombre: 'srv.cita-agendada' },
      acciones: [{ tipo: 'elegir', objetivo: { guia: 'srv-cita-cliente' }, valor: '{mem.clienteId}' }] },
    { id: 'servicio', objetivo: { guia: 'srv-cita-servicio' },
      mensaje: '…un corte de cabello…',
      logrado: { tipo: 'hecho', nombre: 'srv.cita-agendada' },
      acciones: [{ tipo: 'elegir', objetivo: { guia: 'srv-cita-servicio' }, valor: '{mem.servicioId}' }] },
    { id: 'quien', objetivo: { guia: 'srv-cita-profesional' },
      mensaje: '…con Ana.',
      logrado: { tipo: 'hecho', nombre: 'srv.cita-agendada' },
      acciones: [{ tipo: 'elegir', objetivo: { guia: 'srv-cita-profesional' }, valor: '{mem.profesionalId}' }] },
    { id: 'agendar', objetivo: { guia: 'srv-cita-agendar' },
      mensaje: 'La agendo.',
      logrado: { tipo: 'hecho', nombre: 'srv.cita-agendada' },
      acciones: [{ tipo: 'pulsar', objetivo: { guia: 'srv-cita-agendar' } }],
      verifica: 'srv.cita-agendada' },
    { id: 'cita', ruta: '/dashboard/ordenes-de-servicio/agenda', objetivo: { guia: 'srv-cita', clave: '{mem.citaId}' },
      mensaje: 'Llega Mariana. Abro su cita.',
      logrado: { tipo: 'hecho', nombre: 'srv.cita-en-orden' },
      acciones: [{ tipo: 'pulsar', objetivo: { guia: 'srv-cita', clave: '{mem.citaId}' } }],
      despues: { tipo: 'aparece', objetivo: { guia: 'srv-cita-llego' } } },
    { id: 'llego', objetivo: { guia: 'srv-cita-llego' },
      mensaje: '«Llegó»: la cita se vuelve una orden.',
      logrado: { tipo: 'hecho', nombre: 'srv.cita-en-orden' },
      acciones: [{ tipo: 'pulsar', objetivo: { guia: 'srv-cita-llego' } }],
      verifica: 'srv.cita-en-orden' },
    { id: 'cobrar', objetivo: { guia: 'srv-orden-cobrar' },
      mensaje: 'Al terminar, la cobro desde la orden.',
      logrado: { tipo: 'hecho', nombre: 'srv.cobrada' },
      acciones: [{ tipo: 'pulsar', objetivo: { guia: 'srv-orden-cobrar' } }] },
    /* En una estética nadie «autoriza» un corte: se cobra igual. */
    { id: 'igual', objetivo: { guia: 'srv-cobrar-igual' }, opcional: true, limite: 3000,
      mensaje: 'Sin presupuesto que aprobar, cobro directo.',
      logrado: { tipo: 'hecho', nombre: 'srv.cobrada' },
      acciones: [{ tipo: 'pulsar', objetivo: { guia: 'srv-cobrar-igual' } }] },
    { id: 'venta', objetivo: { guia: 'venta-cobrar' },
      mensaje: 'La venta ya trae el corte.',
      logrado: { tipo: 'hecho', nombre: 'srv.cobrada' },
      acciones: [{ tipo: 'pulsar', objetivo: { guia: 'venta-cobrar' } }],
      despues: { tipo: 'aparece', objetivo: { guia: 'venta-recibido' } } },
    { id: 'pago', objetivo: { guia: 'venta-recibido' },
      mensaje: 'En efectivo.',
      logrado: { tipo: 'hecho', nombre: 'srv.cobrada' },
      acciones: [
        { tipo: 'pulsar', objetivo: { guia: 'venta-pago-efectivo' } },
        { tipo: 'escribir', objetivo: { guia: 'venta-recibido' }, texto: '200' },
        { tipo: 'pulsar', objetivo: { guia: 'venta-confirmar-cobro' } },
      ],
      verifica: 'srv.cobrada' },
    { id: 'fin', estado: 'success',
      mensaje: 'Listo. Cita atendida y cobrada, con la comisión para Ana.',
      acciones: [{ tipo: 'pausa', ms: 700 }] },
  ],
};

export const ESCENARIOS: readonly Escenario[] = [
  PRIMER_USO, VENTA, PRODUCTO, MESAS, COCINA, SERVICIOS_ORDENES, SERVICIOS_AGENDA,
  DEMO_RETAIL, DEMO_HOSPITALITY, DEMO_TALLER, DEMO_BELLEZA,
];

export function escenario(id: string): Escenario | null {
  return ESCENARIOS.find(e => e.id === id) ?? null;
}

/** El que se ofrece la primera vez. */
export const ESCENARIO_INICIAL = PRIMER_USO.id;
